[project]
name = "outlook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "exchangelib>=5.5.0",
    "flask>=3.1.0",
    "python-dotenv>=1.0.1",
    "waitress>=3.0.2",
]
