[project]
name = "outlook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "exchangelib>=5.5.0",
    "flask>=3.1.0",
    "icecream>=2.1.3",
    "pysnooper>=1.2.1",
]
